"""initial DigiGates MySQL schema"""
from alembic import op
import sqlalchemy as sa
revision="20260823_0001"; down_revision=None; branch_labels=None; depends_on=None
def timestamps(): return [sa.Column("created_at",sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(),server_default=sa.func.now(),nullable=False)]
def upgrade():
    op.create_table("users",sa.Column("user_id",sa.Integer(),primary_key=True),sa.Column("full_name",sa.String(120),nullable=False),sa.Column("email",sa.String(255),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",sa.Enum("LEARNER","ADMIN",name="userrole"),nullable=False),sa.Column("is_active",sa.Boolean(),server_default="1",nullable=False),*timestamps(),sa.UniqueConstraint("email"))
    op.create_index("ix_users_email","users",["email"],unique=True)
    op.create_table("logic_gates",sa.Column("gate_id",sa.Integer(),primary_key=True),sa.Column("gate_name",sa.String(20),nullable=False,unique=True),sa.Column("description",sa.Text(),nullable=False),sa.Column("input_count",sa.Integer(),nullable=False),sa.Column("boolean_symbol",sa.String(30),nullable=False),sa.Column("expression_pattern",sa.String(100),nullable=False),*timestamps(),sa.CheckConstraint("input_count IN (1,2)",name="ck_gate_input_count"))
    op.create_table("lessons",sa.Column("lesson_id",sa.Integer(),primary_key=True),sa.Column("gate_id",sa.Integer(),sa.ForeignKey("logic_gates.gate_id",ondelete="RESTRICT"),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("theory_content",sa.Text(),nullable=False),sa.Column("lesson_order",sa.Integer(),nullable=False),sa.Column("is_published",sa.Boolean(),server_default="0",nullable=False),*timestamps())
    op.create_index("ix_lessons_gate_id","lessons",["gate_id"]); op.create_index("ix_lessons_published_order","lessons",["is_published","lesson_order"])
    op.create_table("prebuilt_circuits",sa.Column("circuit_id",sa.Integer(),primary_key=True),sa.Column("title",sa.String(180),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("difficulty",sa.String(30),nullable=False),sa.Column("circuit_definition",sa.JSON(),nullable=False),sa.Column("expression",sa.Text(),nullable=False),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("is_published",sa.Boolean(),server_default="0",nullable=False),*timestamps())
    op.create_index("ix_prebuilt_circuits_created_by","prebuilt_circuits",["created_by"]); op.create_index("ix_prebuilt_published_difficulty","prebuilt_circuits",["is_published","difficulty"])
    op.create_table("saved_circuits",sa.Column("saved_circuit_id",sa.Integer(),primary_key=True),sa.Column("learner_id",sa.Integer(),sa.ForeignKey("users.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("circuit_name",sa.String(180),nullable=False),sa.Column("circuit_definition",sa.JSON(),nullable=False),sa.Column("expression",sa.Text(),nullable=False),*timestamps(),sa.UniqueConstraint("learner_id","circuit_name",name="uq_saved_learner_name"))
    op.create_index("ix_saved_circuits_learner_id","saved_circuits",["learner_id"])
    op.create_table("progress",sa.Column("progress_id",sa.Integer(),primary_key=True),sa.Column("learner_id",sa.Integer(),sa.ForeignKey("users.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("lesson_id",sa.Integer(),sa.ForeignKey("lessons.lesson_id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.Enum("NOT_STARTED","IN_PROGRESS","COMPLETED",name="progressstatus"),nullable=False),sa.Column("last_accessed_at",sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column("completed_at",sa.DateTime()),sa.UniqueConstraint("learner_id","lesson_id",name="uq_progress_learner_lesson"))
    op.create_index("ix_progress_learner_id","progress",["learner_id"]); op.create_index("ix_progress_lesson_id","progress",["lesson_id"])
    op.create_table("exercises",sa.Column("exercise_id",sa.Integer(),primary_key=True),sa.Column("lesson_id",sa.Integer(),sa.ForeignKey("lessons.lesson_id",ondelete="RESTRICT")),sa.Column("circuit_id",sa.Integer(),sa.ForeignKey("prebuilt_circuits.circuit_id",ondelete="RESTRICT")),sa.Column("title",sa.String(180),nullable=False),sa.Column("instructions",sa.Text(),nullable=False),sa.Column("exercise_type",sa.String(50),nullable=False),sa.Column("expected_result",sa.JSON(),nullable=False),sa.Column("is_published",sa.Boolean(),server_default="0",nullable=False),*timestamps())
    op.create_index("ix_exercises_lesson_id","exercises",["lesson_id"]); op.create_index("ix_exercises_circuit_id","exercises",["circuit_id"])
    op.create_table("exercise_attempts",sa.Column("attempt_id",sa.Integer(),primary_key=True),sa.Column("exercise_id",sa.Integer(),sa.ForeignKey("exercises.exercise_id",ondelete="RESTRICT"),nullable=False),sa.Column("learner_id",sa.Integer(),sa.ForeignKey("users.user_id",ondelete="RESTRICT"),nullable=False),sa.Column("submitted_answer",sa.JSON(),nullable=False),sa.Column("is_correct",sa.Boolean(),nullable=False),sa.Column("score",sa.Numeric(5,2),nullable=False),sa.Column("attempted_at",sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("score >= 0 AND score <= 100",name="ck_attempt_score"))
    op.create_index("ix_exercise_attempts_exercise_id","exercise_attempts",["exercise_id"]); op.create_index("ix_exercise_attempts_learner_id","exercise_attempts",["learner_id"]); op.create_index("ix_attempt_learner_exercise","exercise_attempts",["learner_id","exercise_id"])
def downgrade():
    for table in ["exercise_attempts","exercises","progress","saved_circuits","prebuilt_circuits","lessons","logic_gates","users"]: op.drop_table(table)
